src/cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_view, name='cart'),
    path('add_item/<slug>/', views.add_item_to_cart, name='add_item'),
    path('remove_one_item/<slug>/', views.remove_one_item, name='remove_one_item'),
    path('remove_all_items/<slug>/', views.remove_all_items, name='remove_all_items'),
]

src/products/urls.py
from django.urls import path
from . import views


app_name= 'products'

urlpatterns = [
    path('', views.products_view , name='list'),
    path('<slug>/', views.product_detail_view, name='detail'),

]

src/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views
from accounts.views import SignUpView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls', namespace="index")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('profile/', include('accounts.urls')),
    path('accounts/signup/', SignUpView.as_view(), name='signup'),
    path('products/', include('products.urls', namespace="proudcts")),
    path('cart/', include('cart.urls', namespace="cart")),
    path('checkout/', include('checkout.urls', namespace="checkout")),
    path('contact/', include('contact.urls', namespace="contact")),
    path('resume/', include('resume.urls', namespace="resume")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/products/models.py
from django.db import models
from django.utils.text import slugify

LABLE_CHOICES =(
('new','new'),
('best_saler', 'best_saler'),
)


class Product(models.Model):
    author = models.CharField(max_length = 250)
    title = models.CharField(max_length = 120, unique=True)
    description = models.TextField()
    current_price = models.FloatField()
    old_price = models.FloatField(blank=True, null=True)
    date_of_publication = models.DateField()
    lable = models.CharField(max_length=50, choices=LABLE_CHOICES)
    related_product = models.ManyToManyField("self")
    slug = models.SlugField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    category = models.ManyToManyField('Category')
    related_product = models.ManyToManyField('self', blank=True, null=True)
    stock = models.IntegerField(default=1)
    def __str__(self):
        return self.title

    def save(self):
        if not self.slug:
            self.slug = slugify(self.title)

        elif self.slug != slugify(self.title):
            self.slug = slugify(self.title)
        super().save()


class Image(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image   = models.ImageField(upload_to = 'books/')
    front   = models.BooleanField(default=False)
    back    = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product.title



class Category(models.Model):
    category   = models.CharField(max_length =120)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.category

src/products/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product,Image, Category


def products_view(request):
    if request.method == 'POST':
        cat = request.POST.get('cat')
        if cat  != 'all':
            try:
                products = Product.objects.filter(category__category=cat)
            except:
                products = Product.objects.all()
        else:
            products = Product.objects.all()
    else:
        products = Product.objects.all()
    categories = Category.objects.all()
    template_name = 'products/books_list.html'
    context = { 'books': products,
                'categories':categories
                }

    return render(request, template_name, context)



def product_detail_view(request, slug):
    product = get_object_or_404(Product, slug=slug)
    categories = Category.objects.all()
    template_name = 'products/single-product.html'
    context = { 'book': product,
                'categories':categories
                }

    return render(request, template_name, context)

src/products/templates/products/single-product.html
{% extends 'base.html' %}
{% load static %}

{% block extra_links %}
<style media="screen">
.tocart{
  height: 20px
}
</style>
{% endblock %}

{% block content %}

        <!-- Start Bradcaump area -->
        <div class="ht__bradcaump__area bg-image--4">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="bradcaump__inner text-center">
                        	<h2 class="bradcaump-title">Shop Single</h2>
                            <nav class="bradcaump-content">
                              <a class="breadcrumb_item" href="index.html">Home</a>
                              <span class="brd-separetor">/</span>
                              <span class="breadcrumb_item active">Shop Single</span>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Bradcaump area -->

        <!-- Start main Content -->
        <div class="maincontent bg--white pt--80 pb--55">
        	<div class="container">
        		<div class="row">
        			<div class="col-lg-9 col-12">
        				<div class="wn__single__product">
        					<div class="row">
        						<div class="col-lg-6 col-12">
        							<div class="wn__fotorama__wrapper">
	        							<div class="fotorama wn__fotorama__action" data-nav="thumbs">
													{% for image in book.image_set.all %}
		        							  <a href="1.jpg"><img src="{{ image.image.url }}" alt=""></a>
														{% endfor %}
	        							</div>
        							</div>
        						</div>
        						<div class="col-lg-6 col-12">
        							<div class="product__info__main">
        								<h1>{{book.title}}</h1>
        								<p>{{book.author}}</p>
        								<div class="price-box">
        									<span>${{book.current_price}}</span>
        								</div>
										<div class="product__overview">

											{{book.description|truncatewords:25|safe}}
        								</div>
        								<div class="box-tocart d-flex">
        									<span>Qty</span>
        									<input id="qty" class="input-text qty" name="qty" min="1" value="1" title="Qty" type="number">
        									<div class="addtocart__actions">
        										<a class="tocart" href="{% url 'cart:add_item' book.slug %}">Add to Cart</a>
        									</div>
        								</div>
										<div class="product_meta">
											<span class="posted_in">Categories:
												{% for cat in book.category.all %}
													<a href="#">{{cat.category}}</a>,
												{% endfor %}
											</span>
										</div>
										<div class="product-share">
											<ul>
												<li class="categories-title">Share :</li>
												<li>
													<a href="#">
														<i class="icon-social-twitter icons"></i>
													</a>
												</li>
												<li>
													<a href="#">
														<i class="icon-social-tumblr icons"></i>
													</a>
												</li>
												<li>
													<a href="#">
														<i class="icon-social-facebook icons"></i>
													</a>
												</li>
												<li>
													<a href="#">
														<i class="icon-social-linkedin icons"></i>
													</a>
												</li>
											</ul>
										</div>
        							</div>
        						</div>
        					</div>
        				</div>
        				<div class="product__info__detailed">
									<div class="pro_details_nav nav justify-content-start" role="tablist">
                    <a class="nav-item nav-link active" data-toggle="tab" href="#nav-details" role="tab">Details</a>
			            </div>
                  <div class="tab__container">

                  	<div class="pro__tab_label tab-pane fade show active" id="nav-details" role="tabpanel">
											<div class="description__attribute">
												<p> {{book.description|safe}}</p>
											</div>
                  	</div>

                  	<div class="pro__tab_label tab-pane fade" id="nav-review" role="tabpanel">
                  	</div>

                  </div>
        				</div>
						<div class="wn__related__product pt--80 pb--50">
							<div class="section__title text-center">
								<h2 class="title__be--2">Related Products</h2>
							</div>
							<div class="row mt--60">
								<div class="productcategory__slide--2 arrows_style owl-carousel owl-theme">
								{% for related in book.related_product.all %}
								<div class="product product__style--3 col-lg-4 col-md-4 col-sm-6 col-12">
									<div class="product__thumb">

										{% for image in  related.image_set.all %}
											{% if image.front %}
												<a class="first__img" href="{% url 'products:detail' related.slug %}"><img src="{{ image.image.url }}" alt="product image"></a>
											{% else %}
													<a class="second__img animation1" href="{% url 'products:detail' related.slug %}"><img style="height:100%" src="https://www.sentinelassam.com/wp-content/uploads/2019/01/521811839-copy.jpg" alt="product image"></a>
											{% endif %}
										{% endfor %}

										{% for image in  related.image_set.all %}
											{% if image.back %}
													<a class="second__img animation1" href="{% url 'products:detail' related.slug %}"><img style="height:100%" src="{{ image.image.url }}" alt="product image"></a>
											{% else %}
													<a class="second__img animation1" href="{% url 'products:detail' related.slug %}"><img style="height:100%" src="https://www.sentinelassam.com/wp-content/uploads/2019/01/521811839-copy.jpg" alt="product image"></a>
											{% endif %}
										{% endfor %}
										<div class="hot__box">
											<span class="hot-label">{{related.lable}}</span>
										</div>
									</div>
									<div class="product__content content--center">
										<h4><a href="single-product.html">{{related.title}}</a></h4>
										<ul class="prize d-flex">
											<li>${{related.current_price}}</li>
											<li class="old_prize">${{related.old_price}}</li>
										</ul>
										<div class="action">
											<div class="actions_inner">
												<ul class="add_to_links">
													<li><a class="cart" href="cart.html"><i class="bi bi-shopping-bag4"></i></a></li>
													<li><a class="wishlist" href="wishlist.html"><i class="bi bi-shopping-cart-full"></i></a></li>
													<li><a class="compare" href="#"><i class="bi bi-heart-beat"></i></a></li>
													<li><a data-toggle="modal" title="Quick View" class="quickview modal-view detail-link" href="#productmodal"><i class="bi bi-search"></i></a></li>
												</ul>
											</div>
										</div>
									</div>
								</div>
								{% endfor %}

								</div>
							</div>
						</div>
        			</div>
        			<div class="col-lg-3 col-12 md-mt-40 sm-mt-40">
        				<div class="shop__sidebar">
        					<aside class="wedget__categories poroduct--cat">
        						<h3 class="wedget__title">Product Categories</h3>
        						<ul>
											{% for cat in categories %}
                        <li><a href="#">{{cat.category}} <span>(3)</span></a></li>
                      {% endfor %}
        						</ul>
        					</aside>
        				</div>
        			</div>
        		</div>
        	</div>
        </div>
        <!-- End main Content -->
		<!-- Start Search Popup -->
		<div class="box-search-content search_active block-bg close__top">
			<form id="search_mini_form--2" class="minisearch" action="#">
				<div class="field__search">
					<input type="text" placeholder="Search entire store here...">
					<div class="action">
						<a href="#"><i class="zmdi zmdi-search"></i></a>
					</div>
				</div>
			</form>
			<div class="close__wrap">
				<span>close</span>
			</div>
		</div>
{% endblock %}