src/cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_view, name='cart'),
    path('add_item/<slug>/', views.add_item_to_cart, name='add_item'),
    path('remove_one_item/<slug>/', views.remove_one_item, name='remove_one_item'),
    path('remove_all_items/<slug>/', views.remove_all_items, name='remove_all_items'),
]

src/contact/urls.py
from django.urls import path

from . import views

app_name = 'contact'

urlpatterns = [
    path('', views.refund_request , name= 'contact')
]

src/products/urls.py
from django.urls import path
from . import views


app_name= 'products'

urlpatterns = [
    path('', views.products_view , name='list'),
    path('<slug>/', views.product_detail_view, name='detail'),

]

src/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views
from accounts.views import SignUpView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls', namespace="index")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('profile/', include('accounts.urls')),
    path('accounts/signup/', SignUpView.as_view(), name='signup'),
    path('products/', include('products.urls', namespace="proudcts")),
    path('cart/', include('cart.urls', namespace="cart")),
    path('checkout/', include('checkout.urls', namespace="checkout")),
    path('contact/', include('contact.urls', namespace="contact")),
    path('resume/', include('resume.urls', namespace="resume")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/index/templates/home/index.html
{% extends 'base.html' %}
{% load static %}
{% block extra_links %}
<style media="screen">

</style>
{% endblock %}


{% block content %}
    <!-- Start Slider area -->
    <div class="slider-area brown__nav slider--15 slide__activation slide__arrow01 owl-carousel owl-theme">

	        <div class="slide animation__style10 bg-image--1 fullscreen align__center--left">
	            <div class="container">
	            	<div class="row">
	            		<div class="col-lg-12">
	            			<div class="slider__content">
		            			<div class="contentbox">
		            				<h2>Buy <span>your </span></h2>
		            				<h2>favourite <span>Book </span></h2>
		            				<h2>from <span>Here </span></h2>
				                   	<a class="shopbtn" href="#">shop now</a>
		            			</div>
	            			</div>
	            		</div>
	            	</div>
	            </div>
            </div>
            <!-- End Single Slide -->

	        <div class="slide animation__style10 bg-image--7 fullscreen align__center--left">
	            <div class="container">
	            	<div class="row">
	            		<div class="col-lg-12">
	            			<div class="slider__content">
		            			<div class="contentbox">
		            				<h2>Buy <span>your </span></h2>
		            				<h2>favourite <span>Book </span></h2>
		            				<h2>from <span>Here </span></h2>
				                   	<a class="shopbtn" href="#">shop now</a>
		            			</div>
	            			</div>
	            		</div>
	            	</div>
	            </div>
            </div>
            <!-- End Single Slide -->

        </div>


		<!-- Start BEst Seller Area -->
		<section class="wn__product__area brown--color pt--80  pb--30">
			<div class="container">
				<div class="row">
					<div class="col-lg-12">
						<div class="section__title text-center">
							<h2 class="title__be--2">New <span class="color--theme">Products</span></h2>
							<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered lebmid alteration in some ledmid form</p>
						</div>
					</div>
				</div>

				<div class=" border--round arrows_style owl-carousel owl-theme row mt--50">
          {% for product in new_prodoucts %}
					<div class="product product__style--3">

						<div class="col-lg-3 col-md-4 col-sm-6 col-12">
							<div class="product__thumb">
                {% for image in  product.image_set.all %}
                  {% if image.front %}
                    <a class="first__img" href="{% url 'products:detail' product.slug %}"><img src="{{ image.image.url }}" alt="product image"></a>
                  {% else %}
                      <a class="second__img animation1" href="{% url 'products:detail' product.slug %}"><img style="height:100%" src="https://www.sentinelassam.com/wp-content/uploads/2019/01/521811839-copy.jpg" alt="product image"></a>
                  {% endif %}
                {% endfor %}

                {% for image in product.image_set.all %}
                  {% if image.back %}
                      <a class="second__img animation1" href="{% url 'products:detail' product.slug %}"><img style="height:100%" src="{{ image.image.url }}" alt="product image"></a>
                  {% else %}
                      <a class="second__img animation1" href="{% url 'products:detail' product.slug %}"><img style="height:100%" src="https://www.sentinelassam.com/wp-content/uploads/2019/01/521811839-copy.jpg" alt="product image"></a>
                  {% endif %}
                {% endfor %}

								<div class="hot__box">
									<span class="hot-label">{{ product.lable }}</span>
								</div>
							</div>
							<div class="product__content content--center">
								<h4><a href="{% url 'products:detail' product.slug %}">{{ product.title }}</a></h4>
								<ul class="prize d-flex">
									<li class="new_prize">${{ product.current_price }}</li>
									<li class="old_prize">{{ product.old_price }}</li>
								</ul>
								<div class="action">
									<div class="actions_inner">
										<ul class="add_to_links">
											<li><a class="cart" href="{% url 'cart:add_item' product.slug %}"><i class="bi bi-shopping-bag4"></i></a></li>
										</ul>
									</div>
								</div>
							</div>
						</div>
					</div>

          {% endfor %}
				</div>

			</div>
		</section>


		<!-- Start NEwsletter Area -->
		<section class="wn__newsletter__area bg-image--2">
			<div class="container">
				<div class="row">
					<div class="col-lg-7 offset-lg-5 col-md-12 col-12 ptb--150">
						<div class="section__title text-center">
							<h2>Stay With Us</h2>
						</div>
						<div class="newsletter__block text-center">
							<p>Subscribe to our newsletters now and stay up-to-date with new collections, the latest lookbooks and exclusive offers.</p>
							<form action="#">
								<div class="newsletter__box">
									<button> <a href="{% url 'contact:contact' %}">connect me</a> </button>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</section>


		<!-- Start Best Seller Area -->
		<section class="wn__bestseller__area bg--white pt--80  pb--30">
			<div class="container">
				<div class="row">
					<div class="col-lg-12">
						<div class="section__title text-center">
							<h2 class="title__be--2">All <span class="color--theme">Products</span></h2>
							<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered lebmid alteration in some ledmid form</p>
						</div>
					</div>
				</div>
				<div class="row mt--50">

				</div>
				<div class="tab__container mt--60">
					<!-- Start Single Tab Content -->
					<div class="row single__tab tab-pane fade show active" id="nav-all" role="tabpanel">
						<div class="product__indicator--4 arrows_style owl-carousel owl-theme">

              <div class="single__product">
              {% for product in all_prodoucts %}
                <div class="col-lg-3 col-md-4 col-sm-6 col-12">
                  <div class="product product__style--3">
                    <div class="product__thumb">

                      {% for image in  product.image_set.all %}
                        {% if image.front %}
                          <a class="first__img" href="{% url 'products:detail' product.slug %}"><img src="{{ image.image.url }}" alt="product image"></a>
                        {% else %}
                            <a class="second__img animation1" href="{% url 'products:detail' product.slug %}"><img style="height:100%" src="https://www.sentinelassam.com/wp-content/uploads/2019/01/521811839-copy.jpg" alt="product image"></a>
                        {% endif %}
                      {% endfor %}

                      {% for image in product.image_set.all %}
                        {% if image.back %}
                            <a class="second__img animation1" href="{% url 'products:detail' product.slug %}"><img style="height:100%" src="{{ image.image.url }}" alt="product image"></a>
                        {% else %}
                            <a class="second__img animation1" href="{% url 'products:detail' product.slug %}"><img style="height:100%" src="https://www.sentinelassam.com/wp-content/uploads/2019/01/521811839-copy.jpg" alt="product image"></a>
                        {% endif %}
                      {% endfor %}
                      <div class="hot__box">
                        <span class="hot-label">{{product.lable}}</span>
                      </div>
                    </div>
                    <div class="product__content content--center content--center">
                      <h4><a href="{% url 'products:detail' product.slug %}">{{ product.title }}</a></h4>
                      <ul class="prize d-flex">
                        <li class="new_prize">${{product.current_price}}</li>

                        <li class="old_prize">${{product.old_price}}</li>
                      </ul>
                      <div class="action">
                        <div class="actions_inner">
                          <ul class="add_to_links">
                            <li><a class="cart" href="{% url 'cart:add_item' product.slug %}"><i class="bi bi-shopping-bag4"></i></a></li>
                          </ul>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              {% endfor %}

						</div>
					</div>



				</div>
			</div>
		</section>


		<!-- Start Recent Post Area -->
		<section class="wn__recent__post bg--gray ptb--80">
			<div class="container">
				<div class="row">
					<div class="col-lg-12">
						<div class="section__title text-center">
							<h2 class="title__be--2">My <span class="color--theme">Resume</span></h2>
							<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered lebmid alteration in some ledmid form</p>
						</div>
					</div>
				</div>
				<div class="row mt--50">
          {% if sections %}
          {% for section in sections %}
          <div class="col-md-6 col-lg-4 col-sm-12">
            <div class="post__itam">
              <div class="content">
                <h3><a href="blog-details.html">{{ section.title }} </a></h3>
                <p>{{section.content|safe|truncatewords:15}}</p>
                <div class="post__time">
                  <span class="day">{{ section.updated_at }}</span>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
          {% endif %}


				</div>
			</div>
		</section>


		<!-- Best Sale Area -->
		<section class="best-seel-area pt--80 pb--60">
			<div class="container">
				<div class="row">
					<div class="col-lg-12">
						<div class="section__title text-center pb--50">
							<h2 class="title__be--2">Best <span class="color--theme">Seller </span></h2>
							<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered lebmid alteration in some ledmid form</p>
						</div>
					</div>
				</div>
			</div>
			<div class="slider center">
				<!-- Single product start -->
        {% for book in best_sales %}
				<div class="product product__style--3">
					<div class="product__thumb">
            {% for image in  book.image_set.all %}
              {% if image.front %}
                <a class="first__img" href="{% url 'products:detail' book.slug %}"><img src="{{ image.image.url }}" alt="product image"></a>
              {% else %}
                  <a class="second__img animation1" href="{% url 'products:detail' book.slug %}"><img style="height:100%" src="https://www.sentinelassam.com/wp-content/uploads/2019/01/521811839-copy.jpg" alt="product image"></a>
              {% endif %}
            {% endfor %}
					</div>
					<div class="product__content content--center">
						<div class="action">
							<div class="actions_inner">
								<ul class="add_to_links">
									<li><a class="cart" href="{% url 'cart:add_item' book.slug %}"><i class="bi bi-shopping-bag4"></i></a></li>
							</div>
						</div>
					</div>
				</div>

        {% endfor %}

			</div>
		</section>

{% endblock %}