src/cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_view, name='cart'),
    path('add_item/<slug>/', views.add_item_to_cart, name='add_item'),
    path('remove_one_item/<slug>/', views.remove_one_item, name='remove_one_item'),
    path('remove_all_items/<slug>/', views.remove_all_items, name='remove_all_items'),
]

src/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views
from accounts.views import SignUpView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls', namespace="index")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('profile/', include('accounts.urls')),
    path('accounts/signup/', SignUpView.as_view(), name='signup'),
    path('products/', include('products.urls', namespace="proudcts")),
    path('cart/', include('cart.urls', namespace="cart")),
    path('checkout/', include('checkout.urls', namespace="checkout")),
    path('contact/', include('contact.urls', namespace="contact")),
    path('resume/', include('resume.urls', namespace="resume")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/resume/urls.py
from django.urls import path
from . import views


app_name= 'resume'
urlpatterns = [
    path('', views.sections_view, name='sections_list'),
    path('<slug>/',views.section_details_view, name='section_details')

]

src/resume/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.utils.text import slugify

class Section(models.Model):
    title = models.CharField(max_length= 30,unique=True)
    slug = models.SlugField(blank=True, null=True)
    content = RichTextField()
    image = models.FileField(upload_to='resume/')
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def save(self):
        if not self.slug:
            self.slug = slugify(self.title)
        elif self.title != self.slug:
            self.slug = slugify(self.title)
        super().save()



class Comment(models.Model):
    post = models.ForeignKey('Section', on_delete=models.CASCADE, related_name='comments')
    comment = models.TextField()
    name = models.CharField(max_length= 30)
    email = models.EmailField()
    created = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return str(self.email)

src/resume/views.py
from django.shortcuts import render, get_object_or_404
from .models import Section, Comment
from .form import CommentForm

def sections_view(request):
    sections = Section.objects.all()
    template_name = 'resume/resume.html'
    context = {"sections":sections}

    return render(request, template_name, context)


def section_details_view(request, slug):
    section = get_object_or_404(Section, slug=slug)
    comments = Comment.objects.filter(post=section)

    if request.method == 'POST':
        form = CommentForm(request.POST or None)
        if form.is_valid():
            print("yes")
            comment= request.POST.get("comment")
            name= request.POST.get("name")
            email= request.POST.get("email")

            new_comment = Comment(
            post = section,
            comment =comment,
            name =name,
            email =email,
            )

            new_comment.save()
        else:
            print (error)

    template_name = 'resume/resume_details.html'
    context = {"section":section,
                'comments':comments}

    return render(request, template_name, context)

src/resume/templates/resume/resume.html
{% extends "base.html" %}

{% block extra_links %}
<style media="screen">
  .style{
    width: 566px;
    height: 338px;
  }
</style>
{% endblock %}

{% block content %}


        <div class="ht__bradcaump__area bg-image--4">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="bradcaump__inner text-center">
                        	<h2 class="bradcaump-title">Resume Page</h2>
                            <nav class="bradcaump-content">
                              <a class="breadcrumb_item" href="index.html">Home</a>
                              <span class="brd-separetor">/</span>
                              <span class="breadcrumb_item active">Resume</span>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Bradcaump area -->
        <!-- Start Blog Area -->
        <div class="page-blog bg--white section-padding--lg blog-sidebar right-sidebar">
        	<div class="container">
        		<div class="row">
        			<div class="col-lg-12 col-12">
        				<div class="blog-page">
        					<div class="page__header">
        						<h2>Welcome Here</h2>
        					</div>
        					{% for section in sections %}
                  <article class="blog__post d-flex flex-wrap">
                    <div class="thumb">
                      <a href="blog-details.html">
                        <img src="{{ section.image.url }}" alt="blog images" class = 'style'>
                      </a>
                    </div>
                    <div class="content">
                      <h4><a href="{% url 'resume:section_details' section.slug %}">{{ section.title}}</a></h4>
                      <ul class="post__meta">
                        <li>last update : <a href="#">{{ section.updated_at}}</a></li>

                      </ul>
                      <p>{{section.content|safe|truncatewords:15}}</p>
                      <div class="blog__btn">
                        <a href="blog-details.html">read more</a>
                      </div>
                    </div>
                  </article>
                  {% endfor %}

        					<!-- End Single Post -->
        				</div>
        			</div>
        		</div>
        	</div>
        </div>
        <!-- End Blog Area -->
{% endblock %}

src/resume/templates/resume/resume_details.html
{% extends 'base.html' %}
{% load static %}
{% block extra_links %}
<style media="screen">

</style>
{% endblock %}


{% block content %}

	<div class="wrapper" id="wrapper">


        <!-- Start Bradcaump area -->
        <div class="ht__bradcaump__area bg-image--6">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="bradcaump__inner text-center">
                        	<h2 class="bradcaump-title">{{ section.title }} Details</h2>
                            <nav class="bradcaump-content">
                              <a class="breadcrumb_item" href="index.html">Home</a>
                              <span class="brd-separetor">/</span>
                              <span class="breadcrumb_item active">{{section.title}}-Details</span>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Bradcaump area -->
		<div class="page-blog-details section-padding--lg bg--white">
			<div class="container">
				<div class="row">
					<div class="col-lg-12 col-12">
						<div class="blog-details content">
							<article class="blog-post-details">
								<div class="post-thumbnail">
									<img src="{{ section.image.url }}" alt="blog images">
								</div>
								<div class="post_wrapper">
									<div class="post_header">
										<h2>{{ section.title }}</h2>
										<div class="blog-date-categori">
											<ul>
												<li>{{ section.updated_at }}</li>
											</ul>
										</div>
									</div>
									<div class="post_content">
										<p> {{ section.content|safe }}</p>
									</div>
									<hr>
									{% if comments %}
										<ul class="blog_meta">
											<li><a href="#">{{ comments.count }} comments</a></li>
										</ul>
									</div>
								</article>
								<div class="comments_area">
									<ul class="comment__list">
										<li>
											{% for comment in comments %}
											<div class="wn__comment">
												<div class="content">
													<div class="comnt__author d-block d-sm-flex">
														<span><a href="#">name :</a> {{comment.name }}</span>
														<span>/ {{ comment.created }}</span>
													</div>
													<p>{{comment.comment}}</p>
												</div>
											</div>

											<br>
											<hr>
											<br>
											{% endfor %}

										</li>
									</ul>
								</div>
								{% endif %}
							<div class="comment_respond">
								<h3 class="reply_title">Leave a Reply <small><a href="#">Cancel reply</a></small></h3>
								<form class="comment__form" method="post">
									{% csrf_token %}
									<p>Your email address will not be published</p>
									<div class="input__box">
										<textarea name="comment" placeholder="Your comment here"></textarea>
									</div>
									<div class="input__wrapper clearfix">
										<div class="input__box name one--third">
											<input name="name" type="text" placeholder="name">
										</div>
										<div class="input__box email one--third">
											<input name="email" type="email" placeholder="email">
										</div>
									</div>
									<div class="submite__btn">
									<button type="submit" name="button" class= "btn btn-lg btn-danger">Post Comment</button>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

{% endblock %}