src/cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_view, name='cart'),
    path('add_item/<slug>/', views.add_item_to_cart, name='add_item'),
    path('remove_one_item/<slug>/', views.remove_one_item, name='remove_one_item'),
    path('remove_all_items/<slug>/', views.remove_all_items, name='remove_all_items'),
]

src/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views
from accounts.views import SignUpView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls', namespace="index")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('profile/', include('accounts.urls')),
    path('accounts/signup/', SignUpView.as_view(), name='signup'),
    path('products/', include('products.urls', namespace="proudcts")),
    path('cart/', include('cart.urls', namespace="cart")),
    path('checkout/', include('checkout.urls', namespace="checkout")),
    path('contact/', include('contact.urls', namespace="contact")),
    path('resume/', include('resume.urls', namespace="resume")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/cart/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

from checkout.models import Address
from products.models import Product
User = settings.AUTH_USER_MODEL

class CartItem(models.Model):
    user = models.ForeignKey(User , on_delete=models.CASCADE)
    product    = models.ForeignKey(Product , on_delete=models.CASCADE)
    quantity   = models.IntegerField(default=1)
    ordered    = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.product.title

    def total_item_price(self):
        return (self.product.current_price * self.quantity)

    def total_item_discount(self):
        if self.product.old_price:
            return ((self.product.old_price - self.product.current_price) * self.quantity)
        else:
            return 0




"""
1- add item to cart
2- adding billing adress
3- payment
4- being delivered
5- received
6- refunds
"""
class Order(models.Model):
    user = models.ForeignKey(User , on_delete=models.CASCADE)
    products = models.ManyToManyField(CartItem)

    code    = models.CharField(max_length= 25)
    ordered = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True)
    ordered_at = models.DateTimeField(default = timezone.now)

    shipping_address = models.ForeignKey(Address, related_name='shipping_address', on_delete= models.CASCADE, null=True, blank=True)
    billing_address  = models.ForeignKey(Address, related_name='billing_address', on_delete= models.CASCADE, null=True, blank=True)

    in_way   = models.BooleanField(default=False)
    received = models.BooleanField(default=False)

    refund_requested = models.BooleanField(default=False)
    refund_granted   = models.BooleanField(default=False)


    def __str__(self):
        return self.user.username




    def total_order_price(self):
        total = 0
        for product in self.products.all():
            total += product.total_item_price()
        return total


    def total_item_discount(self):
        total = 0
        for product in self.products.all():
            total += product.total_item_discount()
        return total

src/cart/views.py
from django.shortcuts import render, Http404, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from .models import CartItem, Order
from products.models import Product

def cart_view(request):
    order = get_object_or_404(Order, user =request.user, ordered=False)

    template_name = 'cart/cart.html'
    context = {
        'order':order
    }
    return render(request, template_name, context)





@login_required
def add_item_to_cart(request, slug):
    product = get_object_or_404(Product, slug=slug)

    order_item, create = CartItem.objects.get_or_create(user= request.user, product=product)

    order_qs = Order.objects.filter(user= request.user, ordered=False)

    if order_qs.exists():
        order = order_qs[0]

        if order.products.filter(product__slug= product.slug).exists():
            order_item.quantity +=1
            order_item.save()
            return redirect('cart:cart')
        else:
            order.products.add(order_item)
            order.save()
            return redirect('cart:cart')

    else:
        order = Order.objects.create(user=request.user)
        order.products.add(order_item)
        order.save()
        return redirect('cart:cart')


    return redirect('cart:cart')


@login_required
def remove_one_item(request, slug):
    product = get_object_or_404(Product, slug=slug)

    order_item = get_object_or_404(CartItem ,user= request.user, product=product)

    order_qs = Order.objects.filter(user= request.user, ordered=False)

    if order_qs.exists():
        order = order_qs[0]

        if order.products.filter(product__slug= product.slug).exists:
            if order_item.quantity >1:
                order_item.quantity -=1
            else:
                order.products.remove(order_item)
            order_item.save()
            return redirect('cart:cart')
        else:

            return redirect('/')

    else:
        return redirect('/')

    return redirect('cart:cart')


@login_required
def remove_all_items(request, slug):
    product = get_object_or_404(Product, slug=slug)

    order_item = get_object_or_404(CartItem ,user= request.user, product=product)

    order_qs = Order.objects.filter(user= request.user, ordered=False)

    if order_qs.exists():
        order = order_qs[0]

        if order.products.filter(product__slug= product.slug).exists:
            order.products.remove(order_item)
            order_item.save()
            return redirect('cart:cart')
        else:

            return redirect('/')

    else:
        return redirect('/')

    return redirect('cart:cart')

src/cart/templates/cart/cart.html
{% extends 'base.html' %}
{% load static %}
{% block extra_links %}
<style media="screen">
.quantity{
	font-size: 2.5em
}

.fas{
		font-size: 2.5em;
		color: #E59285;
}

</style>
{% endblock %}


{% block content %}

        <!-- Start Bradcaump area -->
        <div class="ht__bradcaump__area bg-image--3">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="bradcaump__inner text-center">
                        	<h2 class="bradcaump-title">Shopping Cart</h2>
                            <nav class="bradcaump-content">
                              <a class="breadcrumb_item" href="index.html">Home</a>
                              <span class="brd-separetor">/</span>
                              <span class="breadcrumb_item active">Shopping Cart</span>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Bradcaump area -->


        <!-- cart-main-area start -->
        <div class="cart-main-area section-padding--lg bg--white">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 col-sm-12 ol-lg-12">
                        <form action="#">
                            <div class="table-content wnro__table table-responsive">
                                <table>
                                    <thead>
                                        <tr class="title-top">
                                            <th class="product-thumbnail">Image</th>
                                            <th class="product-name">Product</th>
                                            <th class="product-price">Price</th>
                                            <th class="product-quantity">Quantity</th>
                                            <th class="product-subtotal">Total</th>
                                            <th class="product-remove">Remove</th>
                                        </tr>
                                    </thead>
                                    <tbody>
																			{% for item in order.products.all %}
                                        <tr>
                                            <td class="product-thumbnail"><a href="#">
																							{% for image in item.product.image_set.all %}
																								{% if image.front %}
																									<img src="{{ image.image.url }}" alt="product img"></a>
																								{% endif %}
																							{% endfor %}
																						</td>
                                            <td class="product-name"><a href="#">{{ item.product.title }}</a></td>
                                            <td class="product-price"><span class="amount">${{ item.product.current_price }} </span></td>
                                            <td class="product-quantity">
																							<a href="{% url 'cart:remove_one_item' item.product.slug %}"><i class="fas fa-angle-down"></i></a>
																							 <span class = 'quantity'> {{item.quantity}} </span>
																							<a href="{% url 'cart:add_item' item.product.slug %}"><i class="fas fa-angle-up"></i></a>
																						</td>
                                            <td class="product-subtotal">${{ item.total_item_price}}</td>
                                            <td class="product-remove"><a href="{% url 'cart:remove_all_items' item.product.slug %}">X</a></td>
                                        </tr>
																				{% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </form>
                        <div class="cartbox__btn">
                            <ul class="cart__btn__list d-flex flex-wrap flex-md-nowrap flex-lg-nowrap justify-content-between">
                                <li><a href="#">Coupon Code</a></li>
                                <li><a href="#">Apply Code</a></li>
                                <li><a href="#">Update Cart</a></li>
                                <li><a href="#">Check Out</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-6 offset-lg-6">
                        <div class="cartbox__total__area">
                            <div class="cartbox-total d-flex justify-content-between">
                                <ul class="cart__total__list">
                                    <li>Cart total</li>
                                    <li>Total discount </li>
                                </ul>
                                <ul class="cart__total__tk">
                                    <li>$70</li>
                                    <li>${{ order.total_item_discount }}</li>
                                </ul>
                            </div>
                            <div class="cart__total__amount">
                                <span>Grand Total</span>
                                <span>${{ order.total_order_price}}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

{% endblock %}